#!/bin/bash

echo " "
echo "*************************************************************"
echo "* Github Variable"
echo "*************************************************************"
echo "* Github Username: $GITHUB_USERNAME"
echo "* Github Token: ${GITHUB_TOKEN:0:20} (Hide in your screenshot)"
echo "* Repository URL: $GITHUB_REPO"
echo "* Repository Branch: $GITHUB_BRANCH"
echo "* Github Auto Pull: $GIT_AUTO_PULL"
echo "*************************************************************"

echo " "
echo "*************************************************************"
echo "* Optional Variable"
echo "*************************************************************"
echo "* Shell Access: $SHELL_ACCESS"
echo "* Auto Install Package: $AUTO_INSTALL_PACKAGE"
echo "* Skip Overwrite Warning: $SKIP_OVERWRITE_WARNING"
echo "*************************************************************"

echo " "
echo "*************************************************************"
echo "* Startup Variable"
echo "*************************************************************"
echo "* Startup Script #1: $STARTUP_SCRIPT_1"
echo "* Startup Script #2: $STARTUP_SCRIPT_2"
echo "*************************************************************"